name: 'Mi Saludador Personalizado'
description: 'Saluda al usuario y crea un archivo de log'

# Definimos parámetros de entrada
inputs:
  nombre-usuario:
    description: 'Nombre de la persona a saludar'
    required: true
    default: 'Juanito Perez'

# Definimos parámetros de salida
outputs:
  estado:
    description: 'Tag version created'
    value: ${{ steps.script.outputs.TAG_VERSION }} # Nombre usado en el script
  version:
    description: 'Tag name created'
    value: ${{ steps.script.outputs.TAG_NAME }}
runs:
  using: "composite" # Indica que es una combinación de pasos
  steps:
    - name: Dar permisos al script
      shell: bash
      # 'github.action_path' es la ruta donde vive tu action, no el repo del usuario
      run: chmod +x ${{ github.action_path }}/script.sh

    - id: script
      name: Tag and get next version number
      shell: bash
      run: ${{ github.action_path }}/script.sh