name: 'Mi Saludador Personalizado'
description: 'Saluda al usuario y crea un archivo de log'

# Definimos parámetros de salida
outputs:
  next_version:
    description: 'Tag version created'
    value: ${{ steps.script.outputs.NEXT_VERSION }} # Nombre usado en el script
  next_tag:
    description: 'Tag name created'
    value: ${{ steps.script.outputs.NEXT_TAG }}
runs:
  using: "composite" # Indica que es una combinación de pasos
  steps:
    - name: Dar permisos al script
      shell: bash
      # 'github.action_path' es la ruta donde vive tu action, no el repo del usuario
      run: chmod +x ${{ github.action_path }}/script.sh

    - id: script
      name: Tag and get next version number
      shell: bash
      run: ${{ github.action_path }}/script.sh